databases:
  - name: mysitepostgresql
    plan: free
    databaseName: apmobackend
    user: ''

services:
  - type: web
    plan: free
    name: apmobackend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn apmobackend.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apmobackend
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4