# Generated by Django 5.1.4 on 2025-01-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_apmo', '0009_category_category_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
