# Generated by Django 5.1.4 on 2025-02-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_apmo', '0010_alter_sermon_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Audio File'),
        ),
    ]
