# Generated by Django 5.1.4 on 2025-02-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_apmo', '0011_alter_sermon_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/sermons/', verbose_name='Audio File'),
        ),
    ]
